=== samuelalonsogil/lenguajeDeMarcas/Boletin2_avanzados/avanzado03.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <!--elemento raÃ­z-->
    <xsd:element name="factura">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="datos_empresa"></xsd:element>
                <xsd:element ref="datos_cliente"></xsd:element>
                <xsd:element ref="datos_factura"></xsd:element>
            </xsd:sequence>
            <xsd:attribute name="n_fac" use="required" type="tipoID"/>
        </xsd:complexType>
    </xsd:element>

    <!--elemento datos_empresa-->
    <xsd:element name="datos_empresa">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nombre" type="xsd:string"/>
                <xsd:element name="dir" type="xsd:string"/>
                <xsd:element ref="poblacion"/>
                <xsd:element name="provincia" type="xsd:string"/>
                <xsd:element name="cif" type="xsd:ID"/>
                <xsd:element ref="telefono"/>
                <xsd:element ref="fax" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <!--elemento tipoPoblacion con contenido y atributo-->
    <xsd:element name="poblacion">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">

                    <xsd:attribute name="cod_postal" type="xsd:int"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>


    <!--elemento telefono-->
    <xsd:element name="telefono">
        <xsd:complexType>
            <xsd:attribute name="num_tel" type="xsd:string" fixed="986300707"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="fax">
        <xsd:complexType>
            <xsd:attribute name="num_fax" type="xsd:int" fixed="696550102"/>
        </xsd:complexType>
    </xsd:element>


    <!--elemento datos_cliente-->
    <xsd:element name="datos_cliente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nombre" type="xsd:string"/>
                <xsd:element name="dir_env" type="xsd:string"/>
                <xsd:element ref="poblacion"/>
                <xsd:element name="provincia" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="n_cli" use="required" type="tipoID"></xsd:attribute>
        </xsd:complexType>
    </xsd:element>


    <!--elemento datos_factura-->
    <xsd:element name="datos_factura">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="fecha" type="xsd:date"/>
                <xsd:element ref="linea" maxOccurs="unbounded"/>
                <xsd:element name="base" type="tipoFlotante"/>
                <xsd:element name="cuota_iva" type="tipoFlotante"/>
                <xsd:element name="total" type="tipoFlotante"/>
            </xsd:sequence>
           <xsd:attributeGroup ref="cuatro"/>
        </xsd:complexType>
    </xsd:element>

    <!--elemento linea-->
    <xsd:element name="linea">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="ref" type="tipoRef"/>
                <xsd:element name="desc" type="tipoDesc"/>
                <xsd:element name="cant" type="xsd:int"/>
                <xsd:element name="precio" type="tipoFlotante"/>
                <xsd:element name="importe" type="tipoFlotante"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <!--definicion tipoFlotante-->
    <xsd:simpleType name="tipoFlotante">
        <xsd:restriction base="xsd:decimal">
            <xsd:fractionDigits value="2"/>
            <xsd:totalDigits value="7"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!--definicion grupo atr cuatro-->
    <xsd:attributeGroup name="cuatro">
        <xsd:attribute name="n_ped" type="tipoID" use="required"/>
        <xsd:attribute name="iva" type="tipoIVA" use="required"/>
        <xsd:attribute name="f_pago" type="tipoPago" use="required"/>
        <xsd:attribute name="moneda" type="xsd:string" fixed="euro"/>
    </xsd:attributeGroup>

    <!--declaracion tipoID-->
    <xsd:simpleType name="tipoID">
        <xsd:restriction base="xsd:int">
            <xsd:totalDigits value="4"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!--tipoPago-->
    <xsd:simpleType name="tipoPago">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="efectivo"/>
            <xsd:enumeration value="tarjeta"/>
            <xsd:enumeration value="plazos"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!--tipoIVA-->
    <xsd:simpleType name="tipoIVA">
        <xsd:restriction base="xsd:positiveInteger">
           <xsd:totalDigits value="2"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <!--tipoRef-->
    <xsd:simpleType name="tipoRef">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="15"/>
            <xsd:minLength value="5"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <!--tipoDescripcion-->
    <xsd:simpleType name="tipoDesc">
        <xsd:restriction base="xsd:string">

        </xsd:restriction>
    </xsd:simpleType>



</xsd:schema>

=== samuelalonsogil/lenguajeDeMarcas/Boletin2_avanzados/avanzado03.xml
<?xml version="1.0" encoding="UTF-8" ?>
<factura n_fac="999"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="avanzado03.xsd">

    <datos_empresa>
        <nombre>Equipos Digitales S.L.</nombre>
        <dir>Av. Valladolid</dir>
        <poblacion cod_postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
        <cif>Q-9876543</cif>
        <telefono num_tel="986300707"/>
        <fax num_fax="696550102"/>
    </datos_empresa>

    <datos_cliente n_cli="879">
        <nombre>Darío, Bueno Gutiérrez</nombre>
        <dir_env>Av. Oporto nº7 4ºd</dir_env>
        <poblacion cod_postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
    </datos_cliente>


    <datos_factura n_ped="731" iva="16" f_pago="efectivo" moneda="euro">
        <fecha>2005-12-01</fecha>
        <linea>
            <ref>MII93000F/8</ref>
            <desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
            <cant>1</cant>
            <precio>230</precio>
            <importe>266.80</importe>
        </linea>
        <linea>
            <ref>MB8QDIP4</ref>
            <desc>PLACA BASE QDI P4</desc>
            <cant>1</cant>
            <precio>180</precio>
            <importe>208.80</importe>
        </linea>
        <linea>
            <ref>MEDD512M32</ref>
            <desc>DIMM DDR 512MB 3200</desc>
            <cant>2</cant>
            <precio>40</precio>
            <importe>92.80</importe>
        </linea>
        <linea>
            <ref>HD250GSA7</ref>
            <desc>DISCO DURO 250GB S-ATA 7200</desc>
            <cant>4</cant>
            <precio>120</precio>
            <importe>556.80</importe>
        </linea>
        <base>970.00</base>
        <cuota_iva>155.20</cuota_iva>
        <total>1125.20</total>
    </datos_factura>
</factura>

<!--Avanzado03 - Dado el siguiente documento Definir un XML schema que valide este
documento, teniendo en cuenta las siguientes características: 

 El número de factura (n_fac), número de cliente (n_cli) y número de pedido (n_ped) son
del tipo “tipoID”, que se define como un entero positivo de 4 cifras. Estos atributos son
obligatorios. No tienen por qué ser únicos dentro del documento. 
 Los números de teléfono (telefono) y fax (fax) de la empresa no tienen porqué aparecer
en la factura, pero siempre que lo hagan deberán tener los mismos valores (teléfono
917776688, fax 917776699). 
 La forma de pago puede tomar los valores “efectivo”, “tarjeta” y “plazos”. 
 El elemento fecha es de tipo “date”. 
 La moneda tiene que aparecer siempre, y siempre toma el valor “euro”. 
 El iva tiene que aparecer siempre, y su valor no puede contener caracteres especiales. 
 Las referencias de los artículos son cadenas de entre 5 y 15 caracteres. 
 Las descripciones de los artículos son cadenas entre 1 y 100 caracteres. 
 Los precios son números reales con un máximo de 5 cifras enteras y 2 decimales. 
 Todos los demás valores de tipo real están limitados a 2 cifras decimales. 
 Los códigos postales tienen 5 dígitos. 
 El porcentaje de iva es un número entero positivo de 2 cifras. 
 Se deben utilizar tanto definiciones de tipos de datos, como referencias a elementos. 
 No es necesario crear un espacio de nombres destino para este esquema.-->
